import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the Claude Design sync (see .design-sync/NOTES.md). All
    // three are gitignored build output, not source: ds-bundle/ is the emitted
    // design-system bundle, dist/ the declaration tree that gives it real prop
    // contracts, .ds-sync/ the staged converter scripts and their deps.
    "ds-bundle/**",
    "dist/**",
    ".ds-sync/**",
    "index.d.ts",
    // Sync inputs, not app source. `.design-sync/previews/*.tsx` are preview
    // fixtures whose literal quotes are the content (`size="32"` captions), so
    // Next's app ruleset misreads them; the rest is config and node scripts.
    ".design-sync/**",
    // Session state and background-task worktrees. A worktree is a full second
    // checkout of this repo, so without this any spawned task makes `npm run
    // lint` report the whole codebase twice and fail.
    ".claude/**",
  ]),
]);

export default eslintConfig;
